version: "3.9"

services:
  frontend:
    build:
      context: ../src/frontend
      dockerfile: Dockerfile
    container_name: ollama-frontend
    environment:
      - OLLAMA_SERVICE_HOSTNAME="ollama-nginx" # IP Address do serviço do Ollama
      - OLLAMA_SERVICE_PORT=8010
    ports:
      - "8045:80"
    networks:
      - ollama-net

  ollama-proxy:
    build:
      context: ../
      dockerfile: src/backend/dockerfile
    container_name: ollama-proxy

    environment:
      - OLLAMA_SERVICE_HOSTNAME="ollama-nginx" # IP Address do serviço do Ollama
      - OLLAMA_SERVICE_PORT=8010
      - OLLAMA_URL="http://ollama-nginx:8010"
    ports:
      - 8010:3000
    networks:
      - ollama-net
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  ollama-net:
    driver: bridge
